version: '3'
services:
  backend:
    depends_on:
    - mongo_db
    build:
      context: ./BE
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      # Pass variables to BE app
      # databaseUrl Hardcoded only for quick local testing
      databaseUrl: mongodb://root:123456@mongo_db:27017/ead_ca2?authSource=admin
      databaseName: ead_ca2
      databaseCollection: ead_2024

  frontend:
    depends_on:
    - backend
    build:
      context: ./FE
      dockerfile: ./Dockerfile
    environment:
    # Pass variables to FE app
     exposedPort: 22137
     webservice_host": "backend.test-service-connect"
     webservice_port": 8080
    ports:
      - 22137:22137

  mongo_db:
    image: mongo:5.0.28
    environment:
      # Pass variables for application
      # Only used for testing local
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGODB_DATABASE: ead_ca2
      MONGO_DATABASE_COLLECTION: ead_2024
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

# Persistent volumne for local mongodb setup
volumes:
  mongodb:
